#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=Trainmetatitan
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=0:30:00
#SBATCH --mem=32000M
#SBATCH --output=preprocessdump.out

module purge
module load 2021
module load Anaconda3/2021.05

# /home/barath/blogwriter/AutoBlogWriter
cd $HOME/kg-super-engine/kg-super-engine
eval "$(conda shell.bash hook)"
conda activate kg-super
python3 /home/barath/kg-super-engine/kg-super-engine/build-chronological-dataset/simple_wikidata_db/preprocess_dump.py --input_file /home/barath/kg-super-engine/latest-all.json.gz --out_dir /home/barath/kg-super-engine/compress-wikidata --batch_size 32
