#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=Trainmetatitan
#SBATCH --nodes=1
#SBATCH --cpus-per-task=3
#SBATCH --time=0:30:00
#SBATCH --mem=16000M
#SBATCH --output=condaenvsetup.out

module purge
module load 2021
module load Anaconda3/2021.05

# /home/barath/blogwriter/AutoBlogWriter
cd $HOME/kg-super-engine/kg-super-engine
eval "$(conda shell.bash hook)"
conda env create -f setup_gpu.yml